### ISSUE TITLE
UI Component Frameworks

### ISSUE THREAD

**Issue by michaelkamphausen** [coop-care/terminology#2]
I like to reopen the UI component framework discussion: I observe the need for a framework that covers almost every UI component we will need, in addition to the basic components, and that integrates nicely with Vue by using Vue components.
My aim is to speed up prototyping by spending less time on UI component development, research or integration.

Let’s define some criteria.

Apart from basic UI components like flex layout grid, buttons, inputs and stuff, I see the need for:
- Segmented Controls
- Sliders (Range)
- Tab Bar
- Step Indicator (actually a Tab Bar with special look)
- Tooltips
- …anything else?

We’ll also need line charts, but I suppose we’ll go with D3 or another chart-specific-library here?

Further criteria:
- look & feel, animation
- nice integration as Vue components
- cherry picking / tree shaking of framework components by using ES modules would be nice to have to reduce file size
- file size obviously 😄
- license

Did I miss something?

**Comment by michaelkamphausen** [comment]
I’d like to consider and investigate the following frameworks:
- [BootstrapVue](https://bootstrap-vue.js.org)
- [Onsen UI](https://onsen.io)
- [Vuetify](https://vuetifyjs.com/en/)

Anything else? Opinions, objections?

**Comment by michaelkamphausen** [comment]
BootstrapVue
- ✅ Segmented Control ("Button style radios")
- ✅ Tab Bar
- 🚫 Step Indicator
- ✅ Sliders (input type=range)
- ✅ Tooltips
- ✅ integration as Vue components
- ✅ Cherry picking / tree shaking
- Look & feel: 😒
- File size: depends on cherry picking. Pure Bootstrap (not BootstrapVue): 305 k javascript & css (73 k zipped)
- MIT License
- Stars: 10,190

Onsen UI
- ✅ Segmented Control
- ✅ Tab Bar
- ✅ Sliders
- 🚫 Step Indicator
- ✅ Tooltip ("Popover")
- ✅ integration as Vue components
- ✅ Cherry picking / tree shaking
- Look & feel: platform specific look and feel for iOS and Android
- File size: depends on cherry picking. Pure OnsenUI (without Vue integration): 447 k javascript & css (99 k zipped)
- Apache License 2.0
- Stars: 7,683

Vuetify
- ✅ Segmented Controls ("Button group")
- ✅ Sliders
- ✅ Tab Bar
- ✅ Step Indicator ("Stepper")
- ✅ Tooltips
- ✅ integration as Vue components
- ✅ cherry picking ("a-la-carte installation")
- Look & feel: material design 
- File size: depends on cherry picking. 886 k javascript & css (165 k zipped)
- MIT License
- Stars: 22,087

**Comment by magdaddy** [comment]
Hi Michael, finally I have some time for Omaha now...

I think using a component framework is sensible, and I looked into your suggestions a bit.

File size is important, but not top concern in my opinion, as we are building the desktop version first. And even when we later do mobile, it will be cached by the browser after the first use, and we expect frequent usage. It may also be possible to compile to a native app using cordova...

Onsen UI seems to be geared specifically towards mobile (iOS/Android), so I think we can rule that out.

Bootstrap is a bit dated in look and feel for my taste... would not be my favorite, but it seems to be a solid choice. 

Vuetify looks good - popular, solid community etc.
It seems to be pretty much locked to Material Design though, which would be a con if we would want a native iOS l&f later.

I'd like to also consider [Quasar](https://quasar.dev). Seems to be popular and solid, has all components we need, has support for cordova/electron etc. I will have to look a bit deeper into it as I haven't used it yet.
 
✅ Segmented Control
✅ Tab Bar
✅ Step Indicator
✅ Sliders
✅ Tooltips
✅ integration as Vue components
✅ Cherry picking / tree shaking
Look & feel: seems pretty flexible
File size: depends on cherry picking. Could not find a size for "pure" framework
MIT License
Stars: 12,300

So my favorites would be Vuetify or Quasar, but I need to do a little more research.
What about you?

**Comment by michaelkamphausen** [comment]
My favorite is Vuetify for the completeness of components so far, but I didn't have a closer look into Quasar yet. On the first glance Quasar seems to offer at least the same level of completeness and I like the look of it a bit more.

I played around with Vuetify today, trying to build a searchable problem / intervention target selection component based on it's TreeView. I missed options to customise the appearance of each item cell with title text, description text etc. and found this is not possible without changing the code of the whole component. I will try the same tomorrow with Quasar's Tree component which looks more promising on that matter.

**Comment by michaelkamphausen** [comment]
We decided to go with Quasar because of smaller advantages in completeness, flexibility and design over Vuetify.
